name: flask_env
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=1.1.1w=h2bbff1b_0
  - pip=25.3=pyhc872135_0
  - python=3.11.0=h966fe2a_3
  - setuptools=80.9.0=py311haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - bcrypt==5.0.0
      - blinker==1.9.0
      - faker==40.1.2
      - flask==3.1.2
      - flask-cors==6.0.2
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - mysql-connector-python==9.5.0
      - tzdata==2025.3
      - werkzeug==3.1.5
prefix: D:\miniconda3\envs\flask_env
